### ISSUE TITLE
Bug: export command not creating intermediate folders

### ISSUE THREAD

**Issue by hehesky** [redhat-nfvpe/helm-ansible-template-exporter#52]
`FATA[0000] open workspace/my-role/defaults/main.yml: no such file or directory`

The export command is not creating any of intermediate folders (including the `myrole` base folder and any sub-structural folder like "defaults", "templates" etc)

**Comment by hehesky** [comment]
Seems to be related to ansible-galaxy version. Please update the doc. Closing now

**Comment by ryandgoulding** [comment]
@hehesky can you please provide the command you are running?  Also, can you confirm that you have ansible-galaxy installed per https://github.com/redhat-nfvpe/helm-ansible-template-exporter#runtime-dependencies?

**Comment by ryandgoulding** [comment]
@hehesky Which version of ansible-galaxy are you using?

**Comment by hehesky** [comment]
I used 2.7. After upgrading to 2.10 it looks ok

**Comment by hehesky** [comment]
I would suggest you guys to specify a minimum version of ansible/ansible-galaxy so people won't get confused like I did.

**Comment by ryandgoulding** [comment]
Thank you for the feedback;  we had intended to eventually containerize this and hide those details.  I will re-open and add in the minimum known version (2.9.6).  Thank you for letting us know!
